apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  labels:
    app: bookstore
  name: bookstore-svc
  namespace: applications
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.124.37
  clusterIPs:
  - 10.108.124.37
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32671
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bookstore
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.16.16.210
